name: fviz
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.11

  # Core scientific stack
  - numpy
  - scipy
  - pandas
  - xarray
  - dask
  - netcdf4
  - h5netcdf
  
    # Plotting
  - matplotlib
  - notebook
  - ffmpeg
  - vtk               # PyVista backend
  - pyvista           # 3D plotting
  - pyvistaqt         # offscreen/movie support (ok on headless too)
  - imageio-ffmpeg    # writer used by PyVista's movie helper
  - ffmpeg            # system ffmpeg (so matplotlib writer also works)

  # Geospatial stack
  - geopandas
  - shapely
  - pyproj
  - rtree
  - cartopy

  # Install the package from GitHub via pip (non-editable)
  - pip
  - pip:
      - "git+https://github.com/mollyjames2/fvcomersem-viz.git"
      # If you use SSH instead:
      # - "git+ssh://git@github.com/mollyjames2/fvcomersem-viz.git"

